export function renderNextSteps(container: HTMLElement) {
    const contentHTML = `
        <div class="relative w-full py-24 overflow-hidden">
            <div class="absolute inset-0 z-0 pointer-events-none">
                <div class="absolute bottom-[-300px] left-1/2 -translate-x-1/2 w-[150%] h-[600px] bg-[#003366] rounded-[50%] blur-[80px] opacity-80"></div>
                <div class="absolute bottom-[-280px] left-1/2 -translate-x-1/2 w-[120%] h-[500px] bg-[#0066cc] rounded-[50%] blur-[60px] opacity-60"></div>
                <div class="absolute bottom-[-250px] left-1/2 -translate-x-1/2 w-[100%] h-[400px] bg-[#4db8ff] rounded-[50%] blur-[50px] opacity-30"></div>
                <div class="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black/20"></div>
            </div>
            <div class="relative z-10 container mx-auto px-4">
                <div class="flex flex-col items-center mb-20">
                    <h2 class="text-4xl md:text-5xl font-bold text-white text-center tracking-tight drop-shadow-lg">Next Steps</h2>
                    <div class="w-48 h-1 bg-white mt-4 rounded-full shadow-[0_0_10px_rgba(255,255,255,0.8)]"></div>
                </div>
                <div class="flex flex-col items-center justify-center">
                    <div class="hidden xl:grid grid-cols-6 gap-y-0 gap-x-8 justify-items-center w-full max-w-7xl -space-y-12"> 
                            <div class="col-start-1 col-span-2"><div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><defs><linearGradient id="hexGradientBlue" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="rgba(34, 211, 238, 0.3)" /><stop offset="100%" stop-color="rgba(59, 130, 246, 0.4)" /></linearGradient><filter id="glow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="1" result="blur" /><feComposite in="SourceGraphic" in2="blur" operator="over" /></filter></defs><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">UNOOSA Hub</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Keep UNOOSA as the central dialogue platform for AI regulation. Clarify the relevance and importance of their participation for maintaining a safer AI regulatory future for their nations.</div></div></div></div>
                            <div class="col-start-3 col-span-2"><div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Soft law launch</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Clear, flexible norms now to avoid future legal gaps. Soft laws can help us with directions to close legal gaps later as we obtain more input from our stakeholders: actors, nations and companies.</div></div></div></div>
                            <div class="col-start-5 col-span-2"><div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Multilingual translations</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Translate brief into multiple languages for accessibility and global reach.</div></div></div></div>
                            <div class="col-start-2 col-span-2 -mt-20"><div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Private Sector Advocacy</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Engage leading private space actors e.g., SpaceX, Blue Origin, Astroscale, Isar Aerospace in AI policy dialogues to mitigate downstream risks.</div></div></div></div>
                            <div class="col-start-4 col-span-2 -mt-20"><div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Channels</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md"><ul class="text-left list-disc pl-4 space-y-2 text-sm"><li>ESA and OECD policy forums (ex. ESA’s AI4EO, UN-SPIDER)</li><li>Space law conferences</li><li>UNOOSA committee meetings</li></ul></div></div></div></div>
                    </div>
                    <div class="hidden md:flex xl:hidden flex-wrap justify-center gap-4 max-w-5xl">
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">UNOOSA Hub</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Keep UNOOSA as the central dialogue platform for AI regulation. Clarify the relevance and importance of their participation for maintaining a safer AI regulatory future for their nations.</div></div></div>
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Soft law launch</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Clear, flexible norms now to avoid future legal gaps. Soft laws can help us with directions to close legal gaps later as we obtain more input from our stakeholders: actors, nations and companies.</div></div></div>
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Multilingual translations</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Translate brief into multiple languages for accessibility and global reach.</div></div></div>
                        <div class="flex justify-center gap-4 w-full -mt-16">
                            <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Private Sector Advocacy</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Engage leading private space actors e.g., SpaceX, Blue Origin, Astroscale, Isar Aerospace in AI policy dialogues to mitigate downstream risks.</div></div></div>
                            <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Channels</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md"><ul class="text-left list-disc pl-4 space-y-2 text-sm"><li>ESA and OECD policy forums (ex. ESA’s AI4EO, UN-SPIDER)</li><li>Space law conferences</li><li>UNOOSA committee meetings</li></ul></div></div></div>
                        </div>
                    </div>
                    <div class="md:hidden flex flex-col items-center gap-8">
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">UNOOSA Hub</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Keep UNOOSA as the central dialogue platform for AI regulation. Clarify the relevance and importance of their participation for maintaining a safer AI regulatory future for their nations.</div></div></div>
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Private Sector Advocacy</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Engage leading private space actors e.g., SpaceX, Blue Origin, Astroscale, Isar Aerospace in AI policy dialogues to mitigate downstream risks.</div></div></div>
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Soft law launch</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Clear, flexible norms now to avoid future legal gaps. Soft laws can help us with directions to close legal gaps later as we obtain more input from our stakeholders: actors, nations and companies.</div></div></div>
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Channels</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md"><ul class="text-left list-disc pl-4 space-y-2 text-sm"><li>ESA and OECD policy forums (ex. ESA’s AI4EO, UN-SPIDER)</li><li>Space law conferences</li><li>UNOOSA committee meetings</li></ul></div></div></div>
                        <div class="relative w-72 h-80 flex-shrink-0 group transition-transform hover:scale-105 duration-300"><svg class="absolute inset-0 w-full h-full drop-shadow-xl" viewBox="0 0 100 115" fill="none" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none"><path d="M50 0 L100 28 L100 87 L50 115 L0 87 L0 28 Z" fill="url(#hexGradientBlue)" stroke="rgba(165, 243, 252, 0.6)" stroke-width="1.5" filter="url(#glow)" class="transition-all duration-300 group-hover:stroke-white group-hover:stroke-[2px] group-hover:fill-cyan-600/40"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10"><h3 class="text-lg font-bold text-white mb-3 uppercase tracking-wider border-b border-cyan-200/50 pb-1">Multilingual translations</h3><div class="text-sm text-white font-medium leading-relaxed drop-shadow-md">Translate brief into multiple languages for accessibility and global reach.</div></div></div>
                    </div>
                </div>
            </div>
        </div>
    `;
    container.innerHTML = contentHTML;
}
